---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(bruceR)
library(plotly)
HCPA_SC_FC <- import("/GPFS/cuizaixu_lab_permanent/wuguowei/python_code/repeat_code/SC_strength/HCPA_SC_FC.csv")

nperm <- 1000
r.real <- cor(HCPA_SC_FC$sc,HCPA_SC_FC$fc,method = "spearman")
r.per <- replicate (nperm, expr = cor (x = HCPA_SC_FC$sc, y = sample (HCPA_SC_FC$fc)))
r.per <- data.frame(permutation_R = r.per,ture_R = rep(r.real,1000))

p1<-ggplot(data=HCPA_SC_FC)+geom_point(aes(log(sc),fc,color="#FFE4E1",alpha=0.2))+
   geom_smooth(data = HCPA_SC_FC, aes(x = log(sc), y = fc), method = lm, color = "#FFFFFF", linetype = "dashed") +
         theme_classic()+labs(y = "FC Variability", x = "SC strength") +
        theme(axis.text=element_text(size=20, color='black'), axis.title=element_text(size=20), aspect.ratio = 1)+
  theme(legend.position="none")

p2<-ggplot(data=r.per)+geom_histogram(aes(permutation_R),bins = 30,color = "#999999", fill = "#999999") +
  geom_vline(xintercept = r.per$ture_R, size = 1, color = 'red', linetype = "dashed") +
    theme_classic() + labs(x = "", y = "") +
    theme(axis.text=element_text(size=20, color='black'), aspect.ratio = 1)+
  theme(axis.line.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())+
  scale_y_continuous(expand = c(0, 0))
ggsave('/GPFS/cuizaixu_lab_permanent/wuguowei/python_code/repeat_code/SC_strength/HCPA_SC_FC',plot=p1,width = 5000,height = 3500,dpi = 300)
ggsave('/GPFS/cuizaixu_lab_permanent/wuguowei/python_code/repeat_code/SC_strength/HCPA_SC_FC_permutation',plot=p2,width = 5000,height = 3500,dpi = 300)
```
```{r}
HCPD_SC_FC <- import("/GPFS/cuizaixu_lab_permanent/wuguowei/python_code/repeat_code/SC_strength/HCPD_SC_FC.csv")
nperm <- 1000
r.real <- cor(HCPD_SC_FC$sc,HCPD_SC_FC$fc,method = "spearman")
r.per <- replicate (nperm, expr = cor (x = HCPD_SC_FC$sc, y = sample (HCPD_SC_FC$fc)))
r.per <- data.frame(permutation_R = r.per,ture_R = rep(r.real,1000))

p1 <- ggplot(data=HCPD_SC_FC)+geom_point(aes(log(sc),fc,color="#FFE4E1",alpha=0.2))+
   geom_smooth(data = HCPD_SC_FC, aes(x = log(sc), y = fc), method = lm, color = "#FFFFFF", linetype = "dashed") +
         theme_classic()+labs(y = "FC Variability", x = "SC strength") +
        theme(axis.text=element_text(size=20, color='black'), axis.title=element_text(size=20), aspect.ratio = 1)+
  theme(legend.position="none")

p2 <- ggplot(data=r.per)+geom_histogram(aes(permutation_R),bins = 30,color = "#999999", fill = "#999999") +
  geom_vline(xintercept = r.per$ture_R, size = 1, color = 'red', linetype = "dashed") +
    theme_classic() + labs(x = "", y = "") +
    theme(axis.text=element_text(size=20, color='black'), aspect.ratio = 1)+
  theme(axis.line.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())+
  scale_y_continuous(expand = c(0, 0))
ggsave('/GPFS/cuizaixu_lab_permanent/wuguowei/python_code/repeat_code/SC_strength/HCPD_SC_FC',plot=p1,width = 5000,height = 3500,dpi = 300)
ggsave('/GPFS/cuizaixu_lab_permanent/wuguowei/python_code/repeat_code/SC_strength/HCPD_SC_FC_permutation',plot=p2,width = 5000,height = 3500,dpi = 300)
```

